### PR TITLE
blink-led_0.1.bb - disable blink led

### PR DESCRIPTION
**Pull request by mwallnoefer**
Atm it is not working correctly, so it makes no sense to have it enabled per default.

### CODE REVIEW

**Comment by htot** [comment]
Thanks. Though AFAIKT the code works fine when we don't have leds.aml loaded:
```
root@edison:~# ls -l /sys/kernel/config/acpi/table     
total 0
drwxr-xr-x 2 root root 0 Jan  1  2000 arduino
drwxr-xr-x 2 root root 0 Jan  1  2000 leds
drwxr-xr-x 2 root root 0 Jan  1  2000 spidev
```

**Comment by htot** [comment]
Try this:
```
root@edison:~# ls -l /sys/kernel/config/acpi/table
total 0
drwxr-xr-x 2 root root 0 Jan  1  2000 arduino
drwxr-xr-x 2 root root 0 Jan  1  2000 leds
drwxr-xr-x 2 root root 0 Jan  1  2000 spidev
root@edison:~# rmdir /sys/kernel/config/acpi/table/leds/
# heartbeat stops
root@edison:~# systemctl start blink-led
# blink-led runs
```

**Comment by mwallnoefer** [comment]
Ah yes, this works indeed. No idea what to do here...Maybe drop the acpi led table per default and keep _blink-led_?

**Comment by htot** [comment]
If I think back, my plan was to have blink-led detect if led signalling is handled by the kernel, and if so, use different triggers depending on cli. So by default we have 'heart beat', during AP mode or ota we have normal on/off blinking (maybe fast and slow modes).

But initially it would be nice to make the errors go away.

**Comment by htot** [comment]
What we need is I think:
```
led = gpiod.Chip("gpiochip0").get_line(40)
+if led.is_used():
+    sys.exit(0)
led.request(consumer=led.owner().name(), type=gpiod.LINE_REQ_DIR_OUT)
```

**Comment by htot** [comment]
I force pushed a solution (I hope) to master and zeus.

**Pull request closed without merging**
