### PR TITLE
remove patches that don't apply

### PR DESCRIPTION
**Pull request by PieterGit**
This is follow up on @htot request to test the new debian scripts. See:
https://github.com/htot/meta-intel-edison/pull/2#issuecomment-565609796

The following patches did not apply with `make setup`

```
  git apply $top_repo_dir/meta-intel-edison/utils/0001-bitbake.conf-building-linux-yocto-5.2-requires-realp.patch
  git apply $top_repo_dir/meta-intel-edison/utils/0001-sudo-Fix-fetching-sources.patch
```

Error 1:
```
...
From /data/my_Edison_Workspace/bbcache/downloads/meta-acpi-mirror
 * branch            eds-5.0.0  -> FETCH_HEAD
Already up to date.
Current branch eds-5.0.0 is up to date.
Applying patch on poky
error: can't open patch '/data/my_Edison_Workspace/meta-intel-edison/utils/0001-bitbake.conf-building-linux-yocto-5.2-requires-realp.patch': No such file or directory
make: *** [Makefile:27: setup] Error 128
```

Errror 2:
```
Current branch eds-5.0.0 is up to date.
Applying patch on poky
error: meta/recipes-extended/sudo/sudo_1.8.23.bb: No such file or directory
make: *** [Makefile:27: setup] Error 1
```

I checked and sudo is now at `sudo_1.8.27.bb` and it has the patch applied.

Documentation issue: to be able to use `bitbake` I needed to install `chrpath texinfo` packages.

### CODE REVIEW

**Comment by PieterGit** [comment]
unfortuately `make debian` fails with:

```
| make: *** [Makefile:850: all] Error 2
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /data/my_Edison_Workspace/out/linux64/build/tmp/work/corei7-32-poky-linux/binutils/2.32.0-r0/temp/log.do_compile.29035)
ERROR: Task (/data/my_Edison_Workspace/out/linux64/poky/meta/recipes-devtools/binutils/binutils_2.32.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2235 tasks of which 2221 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /data/my_Edison_Workspace/out/linux64/poky/meta/recipes-devtools/binutils/binutils_2.32.bb:do_compile
Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
make: *** [Makefile:53: edison-image] Error 1

```

Will try to look into that later, but if you give me a hint, that would be great...

**Comment by htot** [comment]
Thanks for testing. I am running a clean build of warrior (make debian will only work on warrior not on master) myself. First I reverted 21855602 as you found to be needed.

I am surprised that binutils didn't compile in your case. Don't know why that happens yet. Let you know tomorrow.

**Comment by PieterGit** [comment]
Double check with `warrior`: you mean this branch: https://github.com/htot/meta-intel-edison/commits/warrior ? For some reason GitHub lists that branch as updated 2 years ago in https://github.com/htot/meta-intel-edison/branches ? I now see that it's has been updated 13 hours ago.

I now installed all the essential packages from https://www.yoctoproject.org/docs/2.7/ref-manual/ref-manual.html#ubuntu-packages and doing another run. Note that my Ubuntu 19.04 is not in the supported distro list. 

Perhaps it's good to add a link in your docs to 
https://www.yoctoproject.org/docs/2.7/ref-manual/ref-manual.html#required-packages-for-the-build-host to make sure people have all the required packages for the build host. 

Will let you know later.

**Comment by PieterGit** [comment]
No luck yet... Tried warrior branch, but `gcc_8.3.bb:do_compile` fails:

```
| ERROR: Function failed: do_compile (log file is located at /data/my_Edison_Workspace/out/linux64/build/tmp/work/corei7-64-poky-linux/gcc/8.3.0-r0/temp/log.do_compile.16575)
ERROR: Task (/data/my_Edison_Workspace/out/linux64/poky/meta/recipes-devtools/gcc/gcc_8.3.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3381 tasks of which 1149 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /data/my_Edison_Workspace/out/linux64/poky/meta/recipes-devtools/gcc/gcc_8.3.bb:do_compile
Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
make: *** [Makefile:53: edison-image] Error 1
```

The logfile has:
```
...
{standard input}: Assembler messages:
{standard input}:413077: Warning: end of file not at end of a line; newline inserted
{standard input}:414585: Error: unknown pseudo-op: `.lvl3607'
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
x86_64-poky-linux-g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[1]: *** [Makefile:1111: insn-emit.o] Error 1
make[1]: *** Waiting for unfinished jobs....
{standard input}: Assembler messages:
{standard input}:900762: Warning: end of file not at end of a line; newline inserted
{standard input}: Error: .size expression for _ZL19gimple_simplify_267P11code_helperPP9tree_nodePP6gimplePFS2_S2_ES2_S3_9tree_code does not evaluate to a constant
x86_64-poky-linux-g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[1]: *** [Makefile:1111: gimple-match.o] Error 1
rm gcc.pod
make[1]: Leaving directory '/data/my_Edison_Workspace/out/linux64/build/tmp/work/corei7-64-poky-linux/gcc/8.3.0-r0/gcc-8.3.0/build.x86_64-poky-linux.x86_64-poky-linux/gcc'
make: *** [Makefile:4279: all-gcc] Error 2
ERROR: oe_runmake failed
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_compile (log file is located at /data/my_Edison_Workspace/out/linux64/build/tmp/work/corei7-64-poky-linux/gcc/8.3.0-r0/temp/log.do_compile.16575)
```

Perhaps it's some kind of gcc issue, my gcc version is `gcc (Ubuntu 8.3.0-6ubuntu1) 8.3.0`

Now trying to build a 32 bits version, https://github.com/htot/meta-intel-edison/commit/05cfff66e2e7d6ed1d145af382cf44713e71cd2d#diff-62904f4c485c0beb0b9214d94346e6abR7

**Comment by htot** [comment]
Yes, that warrior is the correct one. The problem may be that the patch on top is from 2018?

I just built (clean checkout with the revert on top) without errors (using Ubuntu 19.10). Also debian builds with no error. Now building master.

I don't expect different results from 19.04 (used that myself until 19.10 released).

I guess you are doing make clean && make setup && make image, correct?

(make clean is important after switching branches)

**Comment by PieterGit** [comment]
Cleaned the directories now, perhaps something stale was in there. Now retrying with:

```
git clone https://github.com/htot/meta-intel-edison.git
cd meta-intel-edison
git checkout warrior
git revert 21855602cb7cf329094d2ac53ddff1763d309647
cd ..
ln -s meta-intel-edison/utils/Makefile.mk Makefile
make setup
make image
```

Will also test on Debian 9 or upgrade my system to Ubuntu 19.10

**Comment by htot** [comment]
I think you have the link to the maxkefile in the parent of meta-intel-edison like described here: https://htot.github.io/meta-intel-edison/1.2-Setting-up.html#setting-up? So you would cd .. before running make?

Building master succeeded, I just forced pushed the patch with the revert.

**Comment by PieterGit** [comment]
Yeah, did that. and `Makefile` was linked. Updated my comment. My Udoo Bolt is running quite a bit slower than your build machine...

**Comment by htot** [comment]
So, that means with the revert I pushed this can be closed? 

On the documentation you found `chrpath` and `texinfo` missing. But in the documentation here it is correct: https://htot.github.io/meta-intel-edison/1.1-Prerequisites-for-building.html#building-the-warrior-branches-on-ubuntu-cosmic

Somewhere else needs updating? Or other packages missing?

Your Udoo Bolt seems like a nice machine.

I have 2 desktops available for the built both quad core / 8 thread. One has i7-4770@3.40GHz 8GB RAM, the other i7-3770@3.40GHz 16GB. The most important factor I found (especially as I use btrfs as file system) is using a SSD (build time 2.5h) instead of HDD (8h). Although right now is seems to be CPU limited, or maybe even fan limited (the 3770 core goes up to 100C when building).

**Comment by PieterGit** [comment]
Yes, this pull request can be closed... 
You applied https://github.com/htot/meta-intel-edison/commit/075d358898bb3652f838dcf96d45d064ac2fbb72 on master and
https://github.com/htot/meta-intel-edison/commit/075d358898bb3652f838dcf96d45d064ac2fbb72 on the warrior branch. That fixes this PR.

Off topic: I upgraded to ubuntu 19.10 and it kept failing on the Udoo Bolt.
I ran on a Debian 9 VPS (took some time). That fixed the problem and the compile was succesfull.
Will flash it to an edison, to see if it works. 

Thanks for the support.

**Comment by htot** [comment]
Hmm that is worrying. Why would it fail to build on Udoo Bolt? Seems like a Yocto issue that I don't have. Where you running 64bit Ubuntu?

**Comment by PieterGit** [comment]
Yes,
```
$ uname -a
Linux bolt 5.3.0-24-generic #26-Ubuntu SMP Thu Nov 14 01:33:18 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by htot** [comment]
And you did a `make clean` irc. There is also `make cleansstate`, but I'm not sure what that would do.

**Comment by PieterGit** [comment]
Yeah, had a completely fresh dir on the Udoo Bolt. I will try later, but first want to get the debian image up.

Ok, I got my first debian image on the Edison running! Things I encountered:

* U-boot question
The edison installed `U-Boot 2019.10 (Dec 29 2019 - 16:49:21 +0000)`. Is this a correct U-Boot?
The debians docs page https://htot.github.io/meta-intel-edison/2.6-Building-Debian.html lists
"Don’t forget to update U-Boot and fixup the environment if you haven’t done that already."
I assume the `make debian` updates the U-Boot for the user? Am I correct this is the `2019.10-rc1`?

BTW I think I https://htot.github.io/meta-intel-edison/2.3-Building-and-flashing-U-boot#instructions-for-building lists an outdated version and has an error. It lists `edison-v2019.01`. I think the `edison-` part should be removed, and according to https://github.com/andy-shev/u-boot/releases the latest version is `v2019.07`. It doesn't lists a `v2019.10` (only an rc). So perhaps better this in the docs:

```
git clone https://github.com/andy-shev/u-boot.git
cd u-boot
git checkout v2019.07
```

I needed to install `apt-get install bison flex` to create the u-boot, but then I noticed I already had an updated u-boot on the Edison.

* Troubles with apt

I didn't get apt-get to install packages. Every package says:

````
# apt-get install aptitude
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package aptitude
```

It misses a `/etc/apt/sources.list`. I tried to create on myself but then, I have troubles with the gpg keys and adding a key says: 

```
# apt-key list
Error: gnupg or gnupg2 do not seem to be installed,
Error: but apt-key requires gnupg or gnupg2 for this operation.
```

How should apt-get be bootstrapped?

**Comment by htot** [comment]
I see, the instructions need some updating. I will reread them and fix where needed.

You can build U-Boot outside Yocto, any version is possible then.  But this is only documented for historic reasons.

From inside Yocto I now have 2019.10 in warrior. If you use flashall or Flash Tool Lite, it will flash U-Boot, env, kernel and rootfs. But you can also put rootfs on usb or sdhc manually. In principle it could be U-Boot and env is still on the factory version then. If so it needs updating manually.

If you installed normal image, there will not be a sources.list and you need to create one. You will also need to create your own repository in that case. See https://htot.github.io/meta-intel-edison/5.0-Creating-a-deb-repository.html

If you installed debian image, there is a sources.list pointing to debian repo's as it should.

I admit, I only tested the debian image by installing manually on a usb. I did not try flashall and assumed that just works as `make debian` overwrites the rootfs file in the toflash directory (or at least I believe that it does).

**Comment by PieterGit** [comment]
I noticed that because I build the stuff on the VPS, I should run: 
`@sudo $(CURDIR)/meta-intel-edison/utils/debian_1_create.sh buster` and 
`@sudo $(CURDIR)/meta-intel-edison/utils/debian_2_mkimage.sh buster`
from the `make debian` part.  Working on it.

**Comment by htot** [comment]
? Why not run `make debian`?

That would first `make edison-image`, which also does postbuild (copies files from deploy to toflash).

**Comment by PieterGit** [comment]
Because I can't attach local USB devices to a Unix VPS :)
I managed to create the debian parts and flash it. 
Still fighting getting network on the edison.

```
# connmanctl
connmanctl> enable wifi
Error wifi: Method "SetProperty" with signature "sv" on interface "net.connman.Technology" doesn't exist
connmanctl> agent on
Agent registered
connmanctl> enable wifi
Error wifi: Method "SetProperty" with signature "sv" on interface "net.connman.Technology" doesn't exist
connmanctl> scan wifi
Error /net/connman/technology/wifi: Method "Scan" with signature "" on interface "net.connman.Technology" doesn't exist
connmanctl> scan wifi
Error /net/connman/technology/wifi: Method "Scan" with signature "" on interface "net.connman.Technology" doesn't exist
connmanctl> services
``` 

Found some issues with copying. Now trying to run `make debian` on the generated files from the VPS. Will take some time.

**Comment by htot** [comment]
> Because I can't attach local USB devices to a Unix VPS :)

Yes I get that. But why would you? The files need to be created in the toflash directory, then you copy the whole directory to your local host. And run Flash Tool Lite on that directory.

Even if you build locally you would run `make flash` separately (which I never do because flashall needs sudo on my machine).  

> I managed to create the debian parts and flash it.
> Still fighting getting network on the edison.
> 
> ```
> # connmanctl
> connmanctl> enable wifi
> Error wifi: Method "SetProperty" with signature "sv" on interface "net.connman.Technology" doesn't exist
>```

This is not normal. It looks like you are missing something. Unfortunately I won't be able to help until after Friday (short holiday AFK).

My suggestion until then would be:
1) Build and install yocto image with flashall, check that wifi works
2) Build debian image. Follow instructions to put [additional kernel](https://htot.github.io/meta-intel-edison/2.2-Building-and-installing-the-kernel.html#installing-the-kernel) on emmc and [debian image](https://htot.github.io/meta-intel-edison/2.1-Building-and-installing-the-rootfs.html#installing-the-rootfs-on-a-sd-card) on sdhc. But take edison-image-edison.ext4 from toflash (from deploy is the yocto based image). [Boot](https://htot.github.io/meta-intel-edison/2.2-Building-and-installing-the-kernel.html#booting-the-alternative-kernels) the sdhc.

```
> connmanctl> agent on
> Agent registered
> connmanctl> enable wifi
> Error wifi: Method "SetProperty" with signature "sv" on interface "net.connman.Technology" doesn't exist
> connmanctl> scan wifi
> Error /net/connman/technology/wifi: Method "Scan" with signature "" on interface "net.connman.Technology" doesn't exist
> connmanctl> scan wifi
> Error /net/connman/technology/wifi: Method "Scan" with signature "" on interface "net.connman.Technology" doesn't exist
> connmanctl> services
> ```

**Comment by htot** [comment]
> I admit, I only tested the debian image by installing manually on a usb. I did not try flashall and assumed that just works as `make debian` overwrites the rootfs file in the toflash directory (or at least I believe that it does).

I now also tested by flashing to the emmc. I used Flash Tool Lite which should be the same as doing `flashall --recovery` followed by `flashall`. I noted that sometimes flashing fails due to a dfu-util error. Maybe the version included with Flash Tool Lite is old and has bugs. Anyway, all combinations work fine (Yocto Warrior / Debian Buster installed on emmc / usb).

Connman works too, except on Buster it complains:
```
root@edison:~# connmanctl 
Error getting VPN connections: The name net.connman.vpn was not provided by any .service fileconnmanctl> 
```
The error is harmless, other services (wifi) work fine.

**Pull request closed without merging**
