### PR TITLE
upgrade from thud to warrior for usage with meta-debian

### PR DESCRIPTION
**Pull request by PieterGit**
meta-debian upgraded to warrior, seeing if I can get meta-debian to build for edison platform

work in progress, do not merge yet

### CODE REVIEW

**Comment by PieterGit** [comment]
@htot I'm trying to get meta-intel-edison work together with meta-debian to create a Debian Buster image that works with Intel Edison. The script on https://github.com/htot/meta-intel-edison/blob/master/utils/create-debian-image.sh seems for jessies and I assume it's outdated.

Compile is running now. Please review my PR so far and let me know if I'm in the right direction. I'm a complete Yocto newbie, so please help me if I'm doing stuff wrong.

Currently compiling.  Is this the correct procedure?
```
mkdir ~/warrior
cd ~/warrior
git clone https://github.com/PieterGit/meta-intel-edison.git
git clone -b master https://github.com/meta-debian/meta-debian.git
cd meta-intel-edison
git checkout warrior
git clone -b master https://github.com/meta-debian/meta-debian.git
cd ..
ln -s meta-intel-edison/utils/Makefile.mk Makefile
make setup
cd ~/warrior/out/linux64
source poky/oe-init-build-env
<<change build/conf/bblayers.conf and build/conf/local.conf>>
bitbake core-image-minimal
```

**Comment by PieterGit** [comment]
Fails with `ERROR: gcc-source-8.3.0-8.3.0-r0 do_fetch: Fetcher failure for URL: 'http://ftp.debian.org/debian/pool/main/g/gcc-8/gcc-8_8.3.0-5.dsc;name=gcc-8_8.3.0-5.dsc'. Unable to fetch URL from any source.`. Need to find out how to use `gcc-8_8.3.0-6` in `ERROR: Task (/home/pietergit/warrior/meta-debian/recipes-debian/gcc/gcc-source_debian.bb:do_fetch) failed with exit code '1'`. Any idea?

**Comment by htot** [comment]
@PieterGit I didn't even know we had a debian script. Must be originating from the original intel image. Let me check if warrior builds, this weekend, then figure out how meta-debian works.

**Comment by htot** [comment]
> Fails with `ERROR: gcc-source-8.3.0-8.3.0-r0 do_fetch: Fetcher failure for URL: 'http://ftp.debian.org/debian/pool/main/g/gcc-8/gcc-8_8.3.0-5.dsc;name=gcc-8_8.3.0-5.dsc'. Unable to fetch URL from any source.`. Need to find out how to use `gcc-8_8.3.0-6` in `ERROR: Task (/home/pietergit/warrior/meta-debian/recipes-debian/gcc/gcc-source_debian.bb:do_fetch) failed with exit code '1'`. Any idea?

It looks like this patch https://github.com/PieterGit/meta-debian/commit/d738e3f4ca1589360cdc334661319d31d5ea8775 shows how to update gcc.

**Comment by PieterGit** [comment]
@htot thanks for the link. Got `meta-debian` compiling with
`DEBIAN_SOURCE_ENABLED` set to `"1"` in `build-dir/conf/local.conf`. Both the `meta-intel-edison` with `warriror` and `meta-debian` fail on `systemd`.

```
ERROR: Command Error: 'quilt --quiltrc /home/pietergit/warrior/out/linux64/build/tmp/work/corei7-32-poky-linux/systemd/1_241+AUTOINC+c1f8ff8d0d-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch systemd-reboot-service.patch
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/units/systemd-reboot.service.in b/units/systemd-reboot.service.in
|index d99bd3e..4517cfe 100644
|--- a/units/systemd-reboot.service.in
|+++ b/units/systemd-reboot.service.in
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
Patch systemd-reboot-service.patch does not apply (enforce with -f)
ERROR: 
DEBUG: Python function patch_do_patch finished
DEBUG: Python function do_patch finished
ERROR: Function failed: patch_do_patch
```

Will investigate later.

**Comment by htot** [comment]
Reboot patch is applied here: https://github.com/htot/meta-intel-edison/blob/master/meta-intel-edison-distro/recipes-core/systemd/systemd_%25.bbappend
What it does is [this](https://htot.github.io/meta-intel-edison/4.1-misc.html#reboot-). 

Edit: as it is non essential you could disable this path for now and see what else breaks next.

**Comment by htot** [comment]
Ok, the patch doesn't apply because systemd-reboot.service.in has been renamed to systemd-reboot.service. Also, the [service] section has been removed and SuccessAction=reboot-force added to the [Unit] section. This should be fairly easy to fix. I'll do that myself after warrior is released, or take your patch if you create on.

**Comment by htot** [comment]
@PieterGit how is this moving along? Is it working?  Could you rebase against master?

**Comment by PieterGit** [comment]
@htot 
It isn't working yet (or I didn't have it working 🤒 )
Didn't have time to look into it, but I hope to work on this in the summer holidays.
Still am motivated to to so, for example to fix https://github.com/jubilinux/jubilinux/issues/6

**Comment by htot** [comment]
@PieterGit I got a bunch of patches into master that now builds warrior 32 bits, and a separate branch warrior (64 bits). You might want to rebase your work on top, maybe it will start working.

**Comment by htot** [comment]
Hi @PieterGit by now we have warrior and PR #4 so there is a separate branch for Stretch and Warrior builds Buster. I would appreciate if you would find time to test this. The approach is not based on building debian from source like meta-debian. Instead the image is compiled from initramfs kernel built by Yocto and debootstrap binaries. Advantage: you don't need to build from source and use Debian binary repo's. As is, it works for Warrior (x86-64) only, not on master (i686).

Docs page is here but is still rough: https://htot.github.io/meta-intel-edison/2.6-Building-Debian.html

**Comment by PieterGit** [comment]
@htot thanks for the info. I hope I will have a look later next week

**Comment by htot** [comment]
We have Warrior in upstream now. I'm closing this one for now, but will be happy to look at a new PR to add meta-debian. In the meanwhile I will be working to move to Zeus. Thanks!

**Pull request closed without merging**
